name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    permissions:
      contents: write # write is required to create releases and push.
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build:production

      - name: Create release branch and bump version + build
        env:
          REF: ${{ github.ref }}
        run: |
          REF_TAG=${GITHUB_REF#refs/tags/}      
          VERSION=${REF_TAG#v}               

          IFS='.-' read -r MAJOR MINOR PATCH TYPE <<< "$VERSION"

          MAJOR=$(printf "%02d" "$MAJOR")
          MINOR=$(printf "%02d" "$MINOR")
          PATCH=$(printf "%02d" "$PATCH")

          # Map prerelease type to number
          case "$TYPE" in
            alpha) TYPE_NUM=01 ;;
            beta)  TYPE_NUM=02 ;;
            rc)    TYPE_NUM=03 ;;
            *)     TYPE_NUM=00 ;;  # stable
          esac

          # Build number
          BUILD="${MAJOR}${MINOR}${PATCH}${TYPE_NUM}"

          sed -i "s/'version' => '.*'/'version' => '${VERSION}'/" config/app.php
          sed -i "s/'build' => '.*'/'build' => '${BUILD}'/" config/app.php

          BRANCH="release/${REF_TAG}"
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git config --local user.name 'Reviactyl CI'
          git checkout -b "$BRANCH"
          git add config/app.php
          git commit -m "ci(release): bump version to ${VERSION} and build to ${BUILD}"
          git push -u origin "$BRANCH"

      - name: Create release archive
        run: |
          rm -rf node_modules tests CODE_OF_CONDUCT.md CONTRIBUTING.md flake.lock flake.nix phpunit.xml shell.nix
          tar -czf panel.tar.gz * .editorconfig .env.example .eslintignore .eslintrc.js .gitignore .prettierrc.json

      - name: Extract changelog
        run: |
          sed -n "/^## ${REF_TAG}/,/^## /{/^## /b;p}" CHANGELOG.md > ./RELEASE_CHANGELOG

      - name: Create checksum and add to changelog
        run: |
          SUM=$(sha256sum panel.tar.gz)
          echo -e "\n#### SHA256 Checksum\n\n\`\`\`\n$SUM\n\`\`\`\n" >> ./RELEASE_CHANGELOG
          echo "$SUM" > checksum.txt

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: ${{ contains(github.ref, 'rc') || contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
          body_path: ./RELEASE_CHANGELOG
          files: |
            panel.tar.gz
            checksum.txt
