name: Unzip File

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Manual trigger

jobs:
  unzip:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Unzip reviactyl.zip
      run: |
        unzip -o reviactyl.zip
        echo "File unzipped successfully"
        
    - name: Show extracted files
      run: ls
